import numpy as np
import matplotlib.pylab as plt
datos= np.genfromtxt("datos.dat")
plt.figure()
plt.title("Inicial")
plt.xlabel("X")
plt.ylabel("Y")
plt.imshow(datos)
plt.savefig("imagen")
#con imshow para graficar los 2d
datos1= np.genfromtxt("datos1.dat")
plt.figure()
plt.title("FIJAS 100")
plt.xlabel("X")
plt.ylabel("Y")
plt.imshow(datos1)
plt.savefig("imagen2")
##para t=2500s
datos2= np.genfromtxt("datos2.dat")
plt.figure()
plt.title("FIJAS 2500")
plt.xlabel("X")
plt.ylabel("Y")
plt.imshow(datos2)
plt.savefig("imagen3")
##libres
datos3= np.genfromtxt("datos3.dat")
plt.figure()
plt.title("LIBRES 100")
plt.xlabel("X")
plt.ylabel("Y")
plt.imshow(datos3)
plt.savefig("imagen4")
##libres t2500
datos4= np.genfromtxt("datos4.dat")
plt.figure()
plt.title("LIBRES 2500")
plt.xlabel("X")
plt.ylabel("Y")
plt.imshow(datos4)
plt.savefig("imagen4")